version: "3.8"

services:
  api:
    build: .
    container_name: inditex-backend-api
    ports:
      - "5000:5000"
    networks:
      - backendnet

networks:
  backendnet:
    external: true
